homeassistant: !include configs/main.yaml

default_config:

logger:
  default: info

recorder: !include  configs/recorder.yaml

frontend:
  themes: !include_dir_merge_named themes


device_tracker: !include configs/router_device_tracker.yaml


notify: !include output/telegram_notifier.yaml
telegram_bot: !include output/telegram_bot.yaml

sensor: !include_dir_merge_list sensors

group: !include groups.yaml
automation: !include_dir_merge_list automation

script: !include scripts.yaml
scene: !include scenes.yaml

input_select: !include input_select.yaml
input_number: !include input_slider.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml

python_script:

yandex_station:
  username: !secret yandex_login
  password: !secret yandex_password

zone: !include configs/zones.yaml