homeassistant: !include includes/homeassistant.yaml

default_config:

logger:
  default: info

recorder: !include configs/recorder.yaml
zone: !include configs/zones.yaml

frontend:
  themes: !include_dir_merge_named themes

input_select: !include includes/input_select.yaml
input_boolean: !include includes/input_boolean.yaml
input_datetime: !include includes/input_datetime.yaml

binary_sensor: !include includes/binary_sensor.yaml

mobile_app:

device_tracker: !include configs/router_device_tracker.yaml

notify: !include includes/output/telegram_notifier.yaml
telegram_bot: !include includes/output/telegram_bot.yaml

sensor: !include_dir_merge_list sensors
group: !include includes/groups.yaml
automation: !include_dir_merge_list automation

script: !include_dir_merge_named scripts

scene: !include includes/scenes.yaml

person: !include includes/person.yaml
ios: !include includes/ios.yaml
switch: !include includes/switch.yaml
climate: !include includes/climate.yaml
http: !include includes/http.yaml
utility_meter: !include includes/utility_meter.yaml

adaptive_lighting: !include includes/adaptive_lighting.yaml

python_script:
