homeassistant:
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 322
  name: Home
  temperature_unit: C
  time_zone: Europe/Moscow
  unit_system: metric

default_config:

notify: !include output/telegram_notifier.yaml
telegram_bot: !include output/telegram_bot.yaml

sensor: !include_dir_merge_list sensors

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
