homeassistant: !include includes/homeassistant.yaml

default_config:
logger:
  default: info

recorder: !include configs/recorder.yaml
zone: !include configs/zones.yaml

frontend:
  themes: !include_dir_merge_named themes

input_select: !include includes/input_select.yaml
input_boolean: !include includes/input_boolean.yaml
input_datetime: !include includes/input_datetime.yaml
input_text: !include includes/input_text.yaml

binary_sensor: !include includes/binary_sensor.yaml

notify: !include includes/output/notify.yaml
telegram_bot: !include includes/output/telegram_bot.yaml

sensor: !include_dir_merge_list sensors
group: !include includes/groups.yaml
automation: !include_dir_merge_list automation

script: !include_dir_merge_named scripts

scene: !include includes/scenes.yaml

person: !include includes/person.yaml
ios: !include includes/ios.yaml
switch: !include includes/switch.yaml
climate: !include includes/climate.yaml
utility_meter: !include includes/utility_meter.yaml
light: !include includes/light.yaml
adaptive_lighting: !include includes/adaptive_lighting.yaml

python_script:

morph_numbers:

yandex_station:
  include:
    - Чайник

yandex_smart_home: !include includes/output/yandex_house_exporter.yaml

mqtt: !include includes/mqtt.yaml

iaquk: !include includes/air_quality.yaml
