homeassistant: !include configs/main.yaml

default_config:

logger:
  default: info

recorder: !include  configs/recorder.yaml

frontend:
  themes: !include_dir_merge_named themes

mobile_app:

device_tracker: !include configs/router_device_tracker.yaml


notify: !include output/telegram_notifier.yaml
telegram_bot: !include output/telegram_bot.yaml

sensor: !include_dir_merge_list sensors

group: !include groups.yaml
automation: !include_dir_merge_list automation

script: !include scripts.yaml
scene: !include scenes.yaml

input_select: !include input_select.yaml
input_number: !include input_slider.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml

python_script:

yandex_station:
  username: !secret yandex_login
  password: !secret yandex_password

zone: !include configs/zones.yaml


switch:
  - platform: flux
    lights:
      - light.midesklamp1s_f86f
    name: Fluxer
    start_time: '10:00'
    stop_time: '0:00'
    start_colortemp: 5000
    sunset_colortemp: 3700
    stop_colortemp: 2800
    brightness: 25.5
    disable_brightness_adjust: true
    mode: mired
    transition: 30
    interval: 60