homeassistant:
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 80
  name: Home
  time_zone: Europe/Moscow
  unit_system: metric

default_config:

logger:
  default: info

device_tracker:
  - platform: xiaomi
    host: 192.168.31.1
    password: !secret xiaomi_router_password

notify: !include output/telegram_notifier.yaml
telegram_bot: !include output/telegram_bot.yaml

sensor: !include_dir_merge_list sensors

group: !include groups.yaml
automation: !include_dir_merge_list automation

script: !include scripts.yaml
scene: !include scenes.yaml

input_select: !include input_select.yaml
input_number: !include input_slider.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml

python_script:
