

homeassistant:
  name: homeassistant
  mac: 08:00:27:5A:91:30
  icon: mdi:server
  picture:
  track: false


alexanders_iphone:
  name: alexanders_iphone
  mac: 36:a6:9c:63:08:2b
  icon:
  picture:
  track: true
