

homeassistant:
  name: homeassistant
  mac: 08:00:27:5A:91:30
  icon: mdi:server
  picture:
  track: false


esp_home-params:
  name: esp_home-params
  mac: 3C:71:BF:2A:B0:77
  icon: 
  picture:
  track: false

alexanders_iphone:
  name: alexanders_iphone
  mac:
  icon:
  picture:
  track: true

alexander_watch:
  name: alexander_watch
  mac:
  icon:
  picture:
  track: true
