title: Home
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: person.alexander
      - entity: sun.sun
    cards:
      - type: weather-forecast
        entity: weather.home
        show_forecast: false
      - type: sensor
        entity: sensor.living_room_humidity
        graph: line
      - type: sensor
        entity: sensor.living_room_humidity
        graph: line
      - type: entities
        entities:
          - entity: input_datetime.weather_notification
          - entity: input_boolean.alarmweekday
  - title: Media
    path: media
    badges: []
    cards:
      - type: media-control
        entity: media_player.samsung_lt24h390
  - title: Network
    path: router
    badges: []
    cards:
      - type: markdown
        content: 'Full router settings in http://router.miwifi.com/ '
        title: Info
      - type: entities
        entities:
          - entity: sensor.speedtest_download
          - entity: sensor.speedtest_upload
          - entity: sensor.speedtest_ping
      - type: gauge
        entity: sensor.speedtest_download
        min: 0
        max: 100
  - title: System
    path: system
    badges: []
    cards:
      - type: gauge
        entity: sensor.processor_use_percent
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 75
      - type: gauge
        entity: sensor.memory_use_percent
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 75
      - type: gauge
        entity: sensor.disk_use_percent_home
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 75
      - type: entities
        entities:
          - sensor.time_online
