- platform: template
  sensors:
    temperature_index:
      device_class: temperature
      value_template: "{{ state_attr('sensor.livingroom_iaq_level','temperature_index')}}"
    humidity_index:
      device_class: humidity
      value_template: "{{ state_attr('sensor.livingroom_iaq_level','humidity_index')}}"
    co2_index:
      device_class: carbon_dioxide
      value_template: "{{ state_attr('sensor.livingroom_iaq_level','co2_index')}}"
    tvoc_index:
      device_class: volatile_organic_compounds
      value_template: "{{ state_attr('sensor.livingroom_iaq_level','tvoc_index')}}"
    pm_index:
      device_class: pm10
      value_template: "{{ state_attr('sensor.livingroom_iaq_level','pm_index')}}"

    temperature_trend:
      value_template: >
        {% if is_state('binary_sensor.air_temperature_trend', 'on') %}
        Rising
        {% else %}
        Falling
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.air_temperature_trend', 'on') %}
        mdi:thermometer-chevron-up
        {% else %}
        mdi:thermometer-chevron-down
        {% endif %}

    humidity_trend:
      value_template: >
        {% if is_state('binary_sensor.air_humidity_trend', 'on') %}
        Rising
        {% else %}
        Falling
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.air_humidity_trend', 'on') %}
        mdi:chevron-up
        {% else %}
        mdi:chevron-down
        {% endif %}

    co2_trend:
      value_template: >
        {% if is_state('binary_sensor.air_co2_trend', 'on') %}
        Rising
        {% else %}
        Falling
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.air_co2_trend', 'on') %}
        mdi:chevron-up
        {% else %}
        mdi:chevron-down
        {% endif %}
