- platform: template
  sensors:
    air_recomendation:
      friendly_name: "Качество воздуха" 
      value_template: >
        {% if states("binary_sensor.cleargrass_air") %} 
        Требуется проветривание 
        {% endif %}
    temperature_recomendation:
      friendly_name: "Температура в комнате" 
      value_template: >
        {% set temperature = states("sensor.temperature_2")|float %}
        {% if temperature < 22 %} 
          Холодно, включи подогрев
        {% elif temperature > 25 %}
          Жарковато, охлаждай
        {% endif %}
    humidity_recomendation:
      friendly_name: "Влажность в комнате" 
      value_template: >
        {% set humidity = states("sensor.humidity_2")|float %}
        {% if humidity < 30 %} 
          Суховато, нужно увлажнять
        {% endif %}

