- platform: template
  sensors:
    energy_cost:
      friendly_name: "Energy cost"
      unit_of_measurement: "RUB/kWh"
      value_template: >
        {% if is_state("select.daily_energy_yard_room_tariff", "night") %}
        3.15
        {% elif is_state("select.daily_energy_yard_room_tariff", "day")  %}
        5.71
        {% else %}
        undefined
        {% endif %}


