- platform: rest
  name: Keenetic CPU Usage
  unique_id: ded628f3-2510-4894-953a-247ad62de663
  unit_of_measurement: "%"
  resource: http://192.168.0.1:81/rci/show/system
  value_template: "{{ value_json.cpuload }}"

- platform: rest
  name: Keenetic RAM Usage
  unique_id: 3a225571-d10f-4405-8e0a-b3015a4273b4
  unit_of_measurement: "%"
  resource: http://192.168.0.1:81/rci/show/system
  value_template: >
    {%- set mem = value_json.memory-%}
    {%- set memfree = mem.split('/')[0]|int(0)-%}
    {%- set memtotal = mem.split('/')[1]|int(1)-%}
    {{ (memfree*100/memtotal)| round(2) }}
