- platform: template
  sensors:
    sun_elevation:
      value_template: >
        {{ state_attr('sun.sun', 'elevation') | float }}
    outside_humidity:
      unit_of_measurement: "%"
      value_template: >
        {{ state_attr('weather.yandex_weather', 'humidity') }}
    outside_temperature:
      unit_of_measurement: "°C"
      value_template: >
        {{ state_attr('weather.yandex_weather', 'temperature') }}
    wind_description:
      friendly_name: "Wind Bofort description"
      value_template: >
        {% set wind_speed = state_attr('weather.yandex_weather','wind_speed') / 3.6 %}

        {% if wind_speed <= 0.2 %}
        Штиль
        {% elif wind_speed >= 0.3 and wind_speed <= 1.6  %}
        Очень легкий ветер
        {% elif wind_speed > 1.6 and wind_speed <= 3.4  %}
        Легкий ветер
        {% elif wind_speed > 3.4 and wind_speed <= 5.5  %}
        Слабый
        {% elif wind_speed > 5.5 and wind_speed <= 8.0  %}
        Умеренный
        {% elif wind_speed > 8.0 and wind_speed <= 10.8  %}
        Свежий
        {% elif wind_speed > 10.8 and wind_speed <= 13.9  %}
        Сильный
        {% elif wind_speed > 13.9 and wind_speed <= 17.2  %}
        Крепкий
        {% elif wind_speed > 17.2 and wind_speed <= 20.8  %}
        Очень крепкий
        {% elif wind_speed > 20.8 and wind_speed <= 28.5  %}
        Шторм
        {% elif wind_speed > 28.5 and wind_speed <= 32.7  %}
        Сильный шторм
        {% elif wind_speed > 32.7  %}
        Ураган
        {% else %}
        undefined
        {% endif %}
