blueprint:
  name: Fallout start notification
  domain: automation
  input:
    precipitation:
      name: Precipitation level
      selector:
        entity:
          domain: sensor

    message_start:
      name: Telegram message
      default: "No message"
      
trigger:
  - platform: numeric_state
    entity_id: !input precipitation
    above: 0.9
    for: 00:01:00
action:
  - service: telegram_bot.send_message
    data:
      message: !input message_start
      