- name: Work
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  icon: mdi:desktop-mac

- name: Univercity
  latitude: !secret latitude_univercity
  longitude: !secret longitude_univercity     
  radius: 250
  icon: mdi:book