- alias: "Apple Watch: Go to sleep"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Go to sleep
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.sleep_mode
        option: "on"

- alias: "Apple Watch: minimal lights living room"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Minimal lights living room
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.living_room_lights
      brightness: 30
      color_name: pink

- alias: "Apple Watch: Turn on adaptive light"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Adaptive light
  action:
    - service: switch.turn_off
      entity_id: switch.animated_scene_flow
    - service: switch.turn_on
      entity_id: switch.adaptive_lighting_adapt_color_bed_room

