- alias: "Apple Watch: Set sleep mode"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Set sleep mode
  action:
    - service: notify.mobile_app_alexanders_phone
      data:
        message: "Apple Watch: set sleep mode."
        data:
          actions:
            - action: "OFF"
              title: "Off"
              icon: 'sfsymbols:sun.max.fill' # specific for apple https://developer.apple.com/sf-symbols/
            - action: "WIND_DOWN"
              title: "Wind down"
              icon: 'sfsymbols:moon.fill'
            - action: "ON"
              title: Sleep
              icon: 'sfsymbols:moon.fill'
    - wait_for_trigger:
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: "OFF"
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: "WIND_DOWN"
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: "ON"
      timeout: "00:00:20"
      continue_on_timeout: false
    - variables:
        event: "{{ wait.trigger.event.data.action.lower() }}"
    - service: input_select.select_option
      data:
        entity_id: input_select.sleep_mode
        option: "{{ event }}"
        

- alias: "Apple Watch: Go to sleep"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Go to sleep
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.sleep_mode
        option: "on"


- alias: "Apple Watch: Turn on gradient"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Flow
  action:
    - service: switch.turn_on
      entity_id: switch.animated_scene_flow


- alias: "Apple Watch: Turn on adaptive light"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Adaptive light
  action:
    - service: switch.turn_off
      entity_id: switch.animated_scene_flow
    - service: switch.turn_on
      entity_id: switch.adaptive_lighting_adapt_color_bed_room