
- alias: "Entering: Alexander"
  trigger:
    platform: state
    to: home
    entity_id: person.alexander
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lamp
        brightness: 150
        color_name: blue

