
- alias: "Entering: Alexander"
  trigger:
    platform: state
    to: home
    entity_id: device_tracker.alexanders_phone
  action:
    - service: light.turn_on
      data:
        entity_id: light.midesklamp1s_f86f
        brightness: 35
        color_temp: 350


- alias: "Entering: Mom"
  trigger:
    platform: state
    to: home
    entity_id: device_tracker.SM-A525F
  action:
    - service: telegram_bot.send_message
      data:
        message: "Мама пришла домой"