
- alias: "Entering: Alexander"
  trigger:
    platform: state
    to: home
    entity_id: person.alexander
  action:
    - service: light.turn_on
      data:
        entity_id: light.midesklamp1s_f86f
        brightness: 35
        color_temp: 350

