- alias: "Entering: Alexander"
  trigger:
    platform: state
    to: home
    entity_id: person.alexander
    for: 00:01:30 # если больше минуты нет дома при текущих настройках - это либо меня и правда нет дома, либо произошло что-то необычное (выключение телефона, выключение электроэнергии, выключение интернета)

  action:
    - service: light.turn_on
      entity_id: light.bedroom_lamp
    - service: telegram_bot.send_message
      data:
        message: "Добро пожаловать домой."
