- alias: "Energy: Switch tariff"
  trigger:
    - platform: time
      at: "07:00:00"
      variables:
        tariff: "day"
    - platform: time
      at: "23:00:00"
      variables:
        tariff: "night"
  action:
    - service: select.select_option
      entity_id: select.daily_energy_yard_room_tariff
      data:
        option: "{{ tariff }}"
