- alias: "Energy: Switch tariff"
  trigger:
    - platform: time
      at: "07:00:00"
      variables:
        tariff: "day"
    - platform: time
      at: "23:00:00"
      variables:
        tariff: "night"
  action:
    - service: select.select_option
      target:
        entity_id: input_select.energy_tariff
      data:
        option: "{{ tariff }}"
    
    - service: select.select_option
      entity_id: utility_meter.daily_energy_yard_room_tariff
      data:
        option: "{{ tariff }}"



- alias: "Energy Debug: Set day tariff"
  trigger:
    - platform: time
      at: "07:00:00"
  action:
    - service: select.select_option
      entity_id: select.daily_energy_yard_room_tariff
      data:
        option: day

- alias: "Energy Debug: Set night tariff"
  trigger:
    - platform: time
      at: "23:00:00"
  action:
    - service: select.select_option
      entity_id: select.daily_energy_yard_room_tariff
      data:
        option: night
