- alias: "Leaving: Alexander"
  trigger:
    platform: state
    to: not_home
    entity_id: person.alexander
  action:
    - service: light.turn_off
      entity_id: light.midesklamp1s_f86f

- alias: "Leaving: Mom"
  trigger:
    platform: state
    to: not_home
    entity_id: person.irina
  action:
    - service: telegram_bot.send_message
      data:
        message: "Мама вышла из дома"
