# нужно, чтобы лампа не включалась, если свет моргнет
- alias: "Light: Auto turn off after power reboot"
  trigger:
  - platform: state
    entity_id: light.bedroom_lamp
    from: 'unavailable'
    to: 'on'
  action:
  - service: light.turn_off
    entity_id: light.bedroom_lamp

