- alias: Mom exiting tracker
  trigger:
    platform: state
    to: not_home
    entity_id: device_tracker.SM-A525F
  action:
    - service: telegram_bot.send_message
      data:
        message: "Мама вышла из дома"

- alias: Mom entering tracker
  trigger:
    platform: state
    to: home
    entity_id: device_tracker.SM-A525F
  action:
    - service: telegram_bot.send_message
      data:
        message: "Мама пришла домой"