- alias: 'Wake Me Up'
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == states('input_number.alarmhour')[:-2] + ':' + states('input_number.alarmminutes')[:-2] }}"
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.alarmweekday
            state: 'on'
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.alarmweekday
            state: 'off'
  action:
    service: telegram_bot.send_message
    data:
      message: "Доброе утро, сейчас на улице {{states('sensor.openweathermap_temperature')}}°C. {{states('sensor.time')}} {{states('input_number.alarmminutes')[:-2]}}"
