- alias: My phone tracker
  trigger:
    platform: state
    to: home
    entity_id: device_tracker.mi9lite
  action:
    - service: light.turn_on
      data:
        entity_id: light.midesklamp1s_f86f
        brightness: 35
        color_temp: 350

- alias: My phone tracker out
  trigger:
    platform: state
    to: not_home
    entity_id: device_tracker.mi9lite
  action:
    - service: light.turn_off
      entity_id: light.midesklamp1s_f86f

- alias: Mom phone tracker
  trigger:
    platform: state
    to: home
    entity_id: device_tracker.mi5s
  action:
    - service: telegram_bot.send_message
      data:
        message: "Мама пришла домой"