- alias: 'Rainy is started'
  use_blueprint:
    path: homeassistant/fallout_start_notification.yaml
    input:
      fallout_sensor: sensor.openweathermap_rain
      message_start: "Похоже, дождь начинается. Уже накапало {{states('sensor.openweathermap_rain')}}мм."


- alias: 'Rain is over'
  use_blueprint:
    path: homeassistant/fallout_end_notification.yaml
    input:
      not_fallout_value: "not raining" # если переменная ниже будет равно этому значению
      fallout_sensor: sensor.openweathermap_rain
      message_end: "Дождь закончился)"
