- alias: "Night mode: Automatically turn off when alarm turns off or at 9AM"
  trigger:
    - platform: time
      at: "09:00"
    - platform: state
      entity_id: input_boolean.alarm_clock
      from: "on"
      to: "off"
  condition:
    condition: state
    entity_id: input_boolean.alarm_clock
    state: "off"
  action:
    entity_id: input_select.sleep_mode
    service: input_select.select_option
    data:
      option: "off"


