- alias: "Sleep mode: Turn off sleep mode at morning"
  trigger:
    - platform: time
      at: "09:00"
  action:
    entity_id: input_select.sleep_mode
    service: input_select.select_option
    data:
      option: "off"


- alias: "Sleep mode: Set wind down lights"
  trigger:
    - platform: time
      at: input_datetime.wind_down
  action:
    entity_id: light.bedroom_lamp
    service: light.turn_on
    data:
      entity_id:
        - light.bedroom_lamp
      brightness: 98
      color_name: red


