
- alias: "Sleep mode: Set wind down"
  trigger:
    - platform: time
      at: input_datetime.wind_down
  action:
    entity_id: input_select.sleep_mode
    service: input_select.select_option
    data:
      option: "wind_down"

- alias: "Sleep mode: Lights"
  trigger:
    - platform: state
      entity_id: input_select.sleep_mode
    - platform: homeassistant
      event: start # in case the states aren't properly restored
  variables:
    sleep_mode: "{{ states('input_select.sleep_mode') }}"
  action:
    choose:
      - conditions: "{{ sleep_mode == 'off' }}"
        sequence:
          - service: switch.turn_off
            entity_id:
              - switch.adaptive_lighting_sleep_mode_bed_room
          - service: light.turn_on
            entity_id: light.bedroom_lamp  

      - conditions: "{{ sleep_mode == 'wind_down' }}"
        sequence:
          - service: switch.turn_on
            entity_id:
              - switch.adaptive_lighting_sleep_mode_bed_room

      - conditions: "{{ sleep_mode == 'on' }}"
        sequence:
          - service: light.turn_off
            entity_id: light.bedroom_lamp

