
- alias: "Sleep mode: Set wind down"
  id: "sleep_mode_set_wind_down"
  trigger:
    platform: time
    at: input_datetime.wind_down
  variables:
    temperature: "{{ states('sensor.living_room_temperature')|int }}"
  action:
    - service: input_select.select_option
      entity_id: input_select.sleep_mode
      data:
        option: "wind_down"
    - service: telegram_bot.send_message
      data:
        message: "В комнате {{ temperature }}°C.
          {% if temperature > 20 %}
          Это жарковато для сна, проветри комнату. Нужно охладить комнату на {{ temperature - 20 }}°C.
          {% elif temperature < 13  %}
          В комнате беспросветный дубак, ты умираешь.
          {% else %}
          Все хорошо, спокойной ночи! 
          {% endif %}"


- alias: "Sleep mode: Lights"
  trigger:
    - platform: state
      entity_id: input_select.sleep_mode
    - platform: homeassistant
      event: start # in case the states aren't properly restored
  variables:
    sleep_mode: "{{ states('input_select.sleep_mode') }}"
    temperature: "{{ states('sensor.living_room_temperature')|int }}"
  action:
    choose:
      - conditions: "{{ sleep_mode == 'off' }}"
        sequence:
          - service: switch.turn_off
            entity_id:
              - switch.adaptive_lighting_sleep_mode_bed_room
          - service: light.turn_on
            entity_id: light.bedroom_lamp  

      - conditions: "{{ sleep_mode == 'wind_down' }}"
        sequence:
          - service: switch.turn_on
            entity_id:
              - switch.adaptive_lighting_sleep_mode_bed_room

      - conditions: "{{ sleep_mode == 'on' }}"
        sequence:
          - service: light.turn_off
            entity_id: light.bedroom_lamp
          - service: telegram_bot.send_message
            data:
              message: "Пора спать! В комнате {{ temperature }}°C. 
                {% if temperature > 20 %}
                К сожалению, ты не охладил комнату. Желательно понизить температуру на {{ temperature - 20 }}°C.
                {% elif temperature < 13  %}
                Ты не нагрел комнату, ты умираешь.
                {% else %}
                Отлично! Это идельная температура для сна, спокойной ночи!
                {% endif %}"