
- alias: "Sleep mode: Set wind down"
  id: "sleep_mode_set_wind_down"
  trigger:
    platform: time
    at: input_datetime.wind_down
  action:
    - service: input_select.select_option
      entity_id: input_select.sleep_mode
      data:
        option: "wind_down"


- alias: "Sleep mode: Lights"
  id: "sleep_mode_changes"
  trigger:
    - platform: state
      entity_id: input_select.sleep_mode
    - platform: homeassistant
      event: start # in case the states aren't properly restored
  variables:
    sleep_mode: "{{ states('input_select.sleep_mode') }}"
  action:
    choose:
      - conditions: "{{ sleep_mode == 'on' }}"
        sequence:
          - service: light.turn_off
            entity_id: light.bedroom_lamp
          - delay: 20 # ждем перед выключением розетки
          # - service: switch.turn_off
          #   entity_id: switch.smart_plug


# можно включать успокаивающую музыку на колонке 