- alias: "Sleep mode: Turn off sleep mode at morning"
  trigger:
    - platform: time
      at: input_datetime.alarm_clock
  action:
    entity_id: input_select.sleep_mode
    service: input_select.select_option
    data:
      option: "off"


- alias: "Sleep mode: Set wind down"
  trigger:
    - platform: time
      at: input_datetime.wind_down
  action:
    service: script.warm_lights


