- alias: 'Snow is started'
  use_blueprint:
    path: homeassistant/fallout_start_notification.yaml
    input:
      precipitation: sensor.openweathermap_snow
      message_start: "Пошел снежок. Уже накапало {{states('sensor.openweathermap_snow')}}мм."


- alias: 'Snow is over'
  use_blueprint:
    path: homeassistant/fallout_end_notification.yaml
    input:
      not_fallout_value: "not snowing" # если переменная ниже будет равно этому значению
      fallout_sensor: sensor.openweathermap_snow
      message_end: "Снег закончился)"

 