- alias: "Telegram: Get current weather"
  description: "Получение температуры"
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: "/start"
  condition: []
  action:
    - service: telegram_bot.send_message
      data:
        message: "
        {% if now().strftime('%H')|int < 7 %}
        Доброй ночи)
        {% elif now().strftime('%H')|int < 12 %}
        Доброе утро)
        {% elif now().strftime('%H')|int < 18 %}
        Хорошего дня)
        {% else %}
        Хорошего вечера)
        {% endif %}
        Сейчас за бортом {{ state_attr('weather.home','temperature') }}°C."
        

