- alias: "Telegram: Help"
  description: "Телеграм справка"
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: "/help"
    - platform: event
      event_type: telegram_command
      event_data:
        command: "/start"
  condition: []
  action:
    - service: telegram_bot.send_message
      data:
        message: "Привет! Я Алиса с дополнениями, можешь мне писать любые сообщения и я отвечу.
        Можешь отправить ссылку на песню или видео, я воспроизведу её. Также доступны манипуляции 'Включи свет', 'Поменяй цвет' или 'Включи чайник'. Наслаждайся!"


