- alias: "Vacation mode: auto turn on"
  initial_state: true
  trigger:
    platform: state
    entity_id: group.persons
    from: home
    to: not_home
    for: "24:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.vacation_mode
    - service: telegram_bot.send_message
      data:
        title: "Vacation mode"
        message: "Никого не было дома 24 часа, переключаю в отпускной режим."

- alias: "Vacation mode: auto turn off"
  initial_state: true
  trigger:
    platform: state
    entity_id: group.persons
    from: not_home
    to: home
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "on"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.vacation_mode
    - service: telegram_bot.send_message
      data:
        title: "Vacation mode"
        message: "Добро пожаловать домой! Вырубаю отпускной режим."
