- id: "Get current weather"
  alias: "Telegram: Get current weather"
  description: "Получение температуры"
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: "/start"
  condition: []
  action:
    - service: telegram_bot.send_message
      data:
        message: "
        {% if now().strftime('%H')|int < 7 %}
        Доброй ночи)
        {% elif now().strftime('%H')|int < 12 %}
        Доброе утро)
        {% elif now().strftime('%H')|int < 18 %}
        Хорошего дня)
        {% else %}
        Хорошего вечера)
        {% endif %}
        Сейчас за бортом {{ states('sensor.openweathermap_temperature') }}°C, прогноз на ближайшее время: {{ states('sensor.openweathermap_forecast_temperature') }}°C. "
        

- alias: 'Morning alarm'
  trigger:
    platform: time
    at: input_datetime.weather_notification
# оповещение в выходные
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.weather_notification_weekdays
            state: 'on'
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.weather_notification_weekdays
            state: 'off'
    
  action:
    service: telegram_bot.send_message
    data:
      message: "{% if now().strftime('%H')|int < 7 %}
        Доброй ночи,
        {% elif now().strftime('%H')|int < 12 %}
        Доброе утро,
        {% elif now().strftime('%H')|int < 18 %}
        Хорошего дня,
        {% else %}
        Хорошего вечера,
        {% endif %}
         сейчас {{states('sensor.openweathermap_temperature_2')}}°C. в Санкт-Петербурге. В Волгограде {{states('sensor.openweathermap_temperature')}}°C"
