
- alias: "Text from yandex station"
  trigger:
    platform: event
    event_type: yandex_station_response
  action:
    service: telegram_bot.send_message
    data:
      target: "{{ trigger.event.data.request_id }}"
      message: "{{ trigger.event.data.text }}"
