- platform: template
  sensors:
    cleargrass_air:
      friendly_name: "Cleargrass Air, плохой воздух"
      device_class: "problem"
      value_template: >
        {{ states('sensor.air_co2')|float > 1500
            or states('sensor.air_pm25')|float > 100
            or states('sensor.air_tvoc')|float > 220 }}
      icon_template: >-
        mdi:biohazard
