sensor:
  - object_id: AIR_co2
    name: "Датчик CO2"
    state_topic: "qingping/582D347012AB/up"
    device_class: carbon_dioxide
    unique_id: "qingping_dioxide"
    value_template: >-
      {{ value_json.sensorData.0.co2.value
          if value_json.type=="17" }}
    unit_of_measurement: "ppm"
    device:
      identifiers: ["582D347012AB"]
      name: "Air monitor"
      model: "CGS1"
      manufacturer: "qingping"
  - object_id: AIR_temperature
    name: "Датчик температуры"
    state_topic: "qingping/582D347012AB/up"
    device_class: temperature
    unique_id: "qingping_temp"
    value_template: >-
      {{ value_json.sensorData.0.temperature.value|round(2)
          if value_json.type=="17" and value_json.sensorData.0.temperature.status==0 }}
    unit_of_measurement: "°C"
    device:
      identifiers: ["582D347012AB"]
      name: "Air monitor"
      model: "CGS1"
      manufacturer: "qingping"
  - object_id: AIR_humidity
    name: "Датчик влажности"
    state_topic: "qingping/582D347012AB/up"
    device_class: humidity
    unique_id: "qingping_hum"
    value_template: >-
      {{ value_json.sensorData.0.humidity.value|round(2)
          if value_json.type=="17" and value_json.sensorData.0.humidity.status==0 }}
    unit_of_measurement: "%"
    device:
      identifiers: ["582D347012AB"]
      name: "Air monitor"
      model: "CGS1"
      manufacturer: "qingping"
  - object_id: AIR_tvoc
    name: "Датчик tvoc"
    state_topic: "qingping/582D347012AB/up"
    device_class: volatile_organic_compounds
    unique_id: "qingping_tvoc"
    value_template: >-
      {{ (value_json.sensorData.0.tvoc.value)|round(3)
          if value_json.type=="17" and value_json.sensorData.0.tvoc.status==0 }}
    unit_of_measurement: "mg/m³"
    device:
      identifiers: ["582D347012AB"]
      name: "Air monitor"
      model: "CGS1"
      manufacturer: "qingping"
  - object_id: AIR_pm10
    name: "Датчик pm10"
    state_topic: "qingping/582D347012AB/up"
    device_class: pm10
    unique_id: "qingping_pm10"
    value_template: >-
      {{ value_json.sensorData.0.pm10.value
          if value_json.type=="17" }}
    unit_of_measurement: "µg/m³"
    device:
      identifiers: ["582D347012AB"]
      name: "Air monitor"
      model: "CGS1"
      manufacturer: "qingping"
  - object_id: AIR_pm25
    name: "Датчик pm25"
    state_topic: "qingping/582D347012AB/up"
    device_class: pm25
    unique_id: "qingping_pm25"
    value_template: >-
      {{ value_json.sensorData.0.pm25.value
          if value_json.type=="17" and value_json.sensorData.0.pm25.status==0 }}
    unit_of_measurement: "µg/m³"
    device:
      identifiers: ["582D347012AB"]
      name: "Air monitor"
      model: "CGS1"
      manufacturer: "qingping"
