- platform: rpi_gpio
  switches:
    - port: 4
      name: "RPi Cooling Fan"
      unique_id: "rpi_cooling_fan"

- platform: animated_scenes
  name: Flow
  lights:
    - light.bedroom_lamp
  brightness: 255
  colors:
    - color_type: rgb_color
      color: [0, 128, 0]
    - color_type: rgb_color
      color: [11, 138, 0]
    - color_type: rgb_color
      color: [24, 149, 0]
    - color_type: rgb_color
      color: [38, 159, 0]
    - color_type: rgb_color
      color: [55, 169, 0]
    - color_type: rgb_color
      color: [72, 179, 0]
    - color_type: rgb_color
      color: [92, 190, 0]
    - color_type: rgb_color
      color: [113, 200, 0]
    - color_type: rgb_color
      color: [136, 210, 0]
    - color_type: rgb_color
      color: [160, 220, 0]
    - color_type: rgb_color
      color: [186, 231, 0]
    - color_type: rgb_color
      color: [214, 241, 0]
    - color_type: rgb_color
      color: [244, 251, 0]
    - color_type: rgb_color
      color: [255, 249, 0]
    - color_type: rgb_color
      color: [255, 238, 0]
    - color_type: rgb_color
      color: [255, 228, 0]
    - color_type: rgb_color
      color: [255, 218, 0]
    - color_type: rgb_color
      color: [255, 207, 0]
    - color_type: rgb_color
      color: [255, 197, 0]
    - color_type: rgb_color
      color: [255, 187, 0]
    - color_type: rgb_color
      color: [255, 176, 0]
    - color_type: rgb_color
      color: [255, 166, 0]
    - color_type: rgb_color
      color: [255, 156, 0]
    - color_type: rgb_color
      color: [255, 146, 0]
    - color_type: rgb_color
      color: [255, 135, 0]
    - color_type: rgb_color
      color: [255, 125, 0]
    - color_type: rgb_color
      color: [255, 115, 0]
    - color_type: rgb_color
      color: [255, 104, 0]
    - color_type: rgb_color
      color: [255, 94, 0]
    - color_type: rgb_color
      color: [255, 84, 0]
    - color_type: rgb_color
      color: [255, 73, 0]
    - color_type: rgb_color
      color: [255, 63, 0]
    - color_type: rgb_color
      color: [255, 53, 0]
    - color_type: rgb_color
      color: [255, 42, 0]
    - color_type: rgb_color
      color: [255, 32, 0]
    - color_type: rgb_color
      color: [255, 22, 0]
    - color_type: rgb_color
      color: [255, 12, 0]
    - color_type: rgb_color
      color: [255, 1, 0]
    - color_type: rgb_color
      color: [255, 0, 18]
    - color_type: rgb_color
      color: [255, 0, 39]
    - color_type: rgb_color
      color: [255, 0, 59]
    - color_type: rgb_color
      color: [255, 0, 80]
    - color_type: rgb_color
      color: [255, 0, 100]
    - color_type: rgb_color
      color: [255, 0, 121]
    - color_type: rgb_color
      color: [255, 0, 142]
    - color_type: rgb_color
      color: [255, 0, 162]
    - color_type: rgb_color
      color: [255, 0, 183]
    - color_type: rgb_color
      color: [255, 0, 203]
    - color_type: rgb_color
      color: [255, 0, 224]
    - color_type: rgb_color
      color: [255, 0, 245]
    - color_type: rgb_color
      color: [245, 0, 255]
    - color_type: rgb_color
      color: [224, 0, 255]
    - color_type: rgb_color
      color: [203, 0, 255]
    - color_type: rgb_color
      color: [183, 0, 255]
    - color_type: rgb_color
      color: [162, 0, 255]
    - color_type: rgb_color
      color: [142, 0, 255]
    - color_type: rgb_color
      color: [121, 0, 255]
    - color_type: rgb_color
      color: [100, 0, 255]
    - color_type: rgb_color
      color: [80, 0, 255]
    - color_type: rgb_color
      color: [59, 0, 255]
    - color_type: rgb_color
      color: [39, 0, 255]
    - color_type: rgb_color
      color: [18, 0, 255]
    - color_type: rgb_color
      color: [0, 2, 255]
    - color_type: rgb_color
      color: [0, 15, 251]
    - color_type: rgb_color
      color: [0, 28, 248]
    - color_type: rgb_color
      color: [0, 41, 244]
    - color_type: rgb_color
      color: [0, 54, 241]
    - color_type: rgb_color
      color: [0, 66, 237]
    - color_type: rgb_color
      color: [0, 77, 234]
    - color_type: rgb_color
      color: [0, 89, 231]
    - color_type: rgb_color
      color: [0, 99, 227]
    - color_type: rgb_color
      color: [0, 110, 224]
    - color_type: rgb_color
      color: [0, 120, 220]
    - color_type: rgb_color
      color: [0, 130, 217]
    - color_type: rgb_color
      color: [0, 139, 214]
    - color_type: rgb_color
      color: [0, 149, 210]
    - color_type: rgb_color
      color: [0, 157, 207]
    - color_type: rgb_color
      color: [0, 166, 203]
    - color_type: rgb_color
      color: [0, 174, 200]
    - color_type: rgb_color
      color: [0, 181, 196]
    - color_type: rgb_color
      color: [0, 188, 193]
    - color_type: rgb_color
      color: [0, 190, 184]
    - color_type: rgb_color
      color: [0, 186, 170]
    - color_type: rgb_color
      color: [0, 183, 158]
    - color_type: rgb_color
      color: [0, 179, 145]
    - color_type: rgb_color
      color: [0, 176, 133]
    - color_type: rgb_color
      color: [0, 172, 121]
    - color_type: rgb_color
      color: [0, 169, 109]
    - color_type: rgb_color
      color: [0, 166, 98]
    - color_type: rgb_color
      color: [0, 162, 87]
    - color_type: rgb_color
      color: [0, 159, 77]
    - color_type: rgb_color
      color: [0, 155, 67]
    - color_type: rgb_color
      color: [0, 152, 57]
    - color_type: rgb_color
      color: [0, 149, 48]
    - color_type: rgb_color
      color: [0, 145, 39]
    - color_type: rgb_color
      color: [0, 142, 31]
    - color_type: rgb_color
      color: [0, 138, 22]
    - color_type: rgb_color
      color: [0, 135, 15]
    - color_type: rgb_color
      color: [0, 131, 7]
    - color_type: rgb_color
      color: [0, 128, 0]
  transition: 5
  change_frequency: 15
  change_amount: all
  change_sequence: True
  animate_color: True
