title: Home
views:
  - path: default_view
    title: Home
    icon: mdi:home
    badges:
      - entity: person.alexander
      - entity: sun.sun
    cards:
      - show_current: true
        show_forecast: true
        type: weather-forecast
        entity: weather.home
      - type: custom:mini-media-player
        entity: media_player.kitchen_speakers
      - type: entities
        entities:
          - binary_sensor.cleargrass_air
      - type: entities
        entities:
          - entity: input_boolean.alarm_clock
          - entity: sensor.alarm_clock
          - entity: sensor.wake_up_light_start_time
          - entity: sensor.weather_notifitcations
          - entity: input_select.sleep_mode
            secondary_info: none
      - type: picture-elements
        elements:
          - type: state-badge
            entity: sensor.air_temperature
            style:
              top: 35%
              left: 15%
              scale: 85%
          - type: state-badge
            entity: sensor.air_humidity
            style:
              top: 35%
              left: 30%
              scale: 85%
        image: >-
          https://sun9-41.userapi.com/impg/ZBqlsc2qDP_hYy7xnqwhCQEXYbvwYvRA_UsNwQ/_P5IL7LPGRk.jpg?size=1406x662&quality=95&sign=8f29b2d623ae0182a0dced2b0a6e5add&type=album
      - type: markdown
        content: >-
          ## Расписание


          | Tables        | Are           |

          | ------------- |:-------------:| 

          | {{ states("sensor.charging_time") }} | Включается розетка для
          зарядки всякого разного |  

          | {{ states("sensor.wake_up_light_start_time") }} | Включается
          лампа-рассвет |  

          | {{ states("sensor.alarm_clock") }} | Будильник, отключается режим
          сна  | 

          | {{ states("sensor.weather_notifitcations") }} | Отправляется
          уведомление о погоде |  

          | {{ states("input_datetime.wind_down") }} | Идет уход ко сну

           
      - type: entities
        entities:
          - entity: sensor.air_recomendation
          - entity: sensor.temperature_recomendation
          - entity: sensor.humidity_recomendation
      - type: media-control
        entity: media_player.yandex_station
      - type: custom:apexcharts-card
        graph_span: 6h
        header:
          show: true
        yaxis:
          - max: 100
            min: 0
            decimals: 0
        series:
          - entity: sensor.outside_humidity
            type: line
            name: Outside Humidity
            group_by:
              func: avg
              duration: 30min
          - entity: sensor.air_humidity
            type: column
            name: Inside Humidity
            group_by:
              func: avg
              duration: 30min
      - type: custom:apexcharts-card
        header:
          show: true
          title: ApexCharts-Card
          show_states: true
          colorize_states: true
        series:
          - entity: sensor.sun_elevation
          - entity: sensor.air_temperature
  - title: Living room
    path: users
    icon: mdi:television
    badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.air_temperature
          - entity: sensor.air_humidity
          - entity: sensor.air_co2
          - entity: sensor.air_tvoc
          - entity: sensor.air_pm25
          - entity: sensor.air_pm10
      - type: vertical-stack
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.living_room_lights
          - shorten_cards: false
            consolidate_entities: true
            child_card: false
            hide_header: false
            show_header_icon: false
            header: ''
            color_wheel: true
            persist_features: false
            brightness: true
            color_temp: true
            white_value: true
            color_picker: true
            speed: true
            intensity: true
            force_features: false
            show_slider_percent: false
            full_width_sliders: false
            brightness_icon: weather-sunny
            white_icon: file-word-box
            temperature_icon: thermometer
            speed_icon: speedometer
            intensity_icon: transit-connection-horizontal
            type: custom:light-entity-card
            entity: light.living_room_lights
            effects_list: false
      - type: entities
        entities:
          - entity: switch.adaptive_lighting_living_room
          - entity: switch.adaptive_lighting_sleep_mode_living_room
      - square: false
        type: grid
        cards:
          - graph: line
            type: sensor
            entity: sensor.air_temperature
            detail: 1
            hours_to_show: 6
          - graph: line
            type: sensor
            entity: sensor.air_humidity
            detail: 1
            hours_to_show: 6
          - graph: line
            type: sensor
            entity: sensor.air_co2
            detail: 1
            hours_to_show: 6
          - graph: line
            type: sensor
            entity: sensor.air_tvoc
            detail: 1
            hours_to_show: 6
          - type: custom:mini-graph-card
            entities:
              - sensor.air_pm10
              - sensor.air_pm25
        columns: 2
      - type: vertical-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.smart_plug_current_power
          - type: entities
            entities:
              - entity: switch.smart_plug
      - type: markdown
        content: >-

          Включить [Plex](http://127.0.0.1:32400/), сюда можно закинуть нужное
          кино, чтобы смотреть с ТВ.
        title: TV
  - title: Bedroom
    path: ''
    icon: mdi:bed-queen
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.bedroom_lamp
            icon: mdi:lamp
            name: Ночник
            show_state: false
          - shorten_cards: false
            consolidate_entities: false
            child_card: true
            hide_header: true
            show_header_icon: false
            header: Midesklamp1s_f86f
            color_wheel: true
            persist_features: false
            brightness: true
            color_temp: true
            white_value: true
            color_picker: true
            speed: true
            intensity: true
            force_features: false
            show_slider_percent: true
            full_width_sliders: false
            brightness_icon: weather-sunny
            white_icon: file-word-box
            temperature_icon: thermometer
            speed_icon: speedometer
            intensity_icon: transit-connection-horizontal
            smooth_color_wheel: true
            type: custom:light-entity-card
            entity: light.bedroom_lamp
            effects_list: false
  - title: Network
    path: router
    icon: mdi:access-point
    badges: []
    cards:
      - type: markdown
        content: 'Full router settings in http://router.miwifi.com/ '
        title: Info
      - type: gauge
        entity: sensor.speedtest_download
        min: 0
        max: 100
      - type: entities
        entities:
          - entity: sensor.speedtest_ping
      - type: custom:mini-graph-card
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
  - title: System
    path: system
    icon: mdi:server
    badges: []
    cards:
      - type: gauge
        entity: sensor.processor_use_percent
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 75
      - type: gauge
        entity: sensor.memory_use_percent
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 75
      - type: gauge
        entity: sensor.disk_use_percent
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 75
      - type: entities
        entities:
          - sensor.time_online
      - type: entities
        entities:
          - entity: binary_sensor.backups_stale
          - entity: sensor.backup_state
      - type: entities
        entities:
          - sensor.disk_free
      - type: entities
        entities:
          - entity: sensor.processor_temperature
          - entity: binary_sensor.rpi_power_status
      - type: thermostat
        entity: climate.rpi_cooling_fan_controller
