title: Home
views:
  - path: default_view
    title: Home
    icon: mdi:home
    badges:
      - entity: person.alexander
      - entity: sun.sun
    cards:
      - show_current: true
        show_forecast: true
        type: weather-forecast
        entity: weather.home
      - type: entities
        entities:
          - entity: input_boolean.alarm_clock
          - entity: sensor.alarm_clock
          - entity: sensor.wake_up_light_start_time
          - entity: sensor.weather_notifitcations
          - entity: input_select.sleep_mode
            secondary_info: none
      - type: vertical-stack
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.bedroom_lamp
            icon: mdi:lamp
            name: Ночник
            show_state: false
          - shorten_cards: false
            consolidate_entities: false
            child_card: true
            hide_header: true
            header: Midesklamp1s_f86f
            color_wheel: true
            persist_features: false
            brightness: true
            color_temp: true
            white_value: true
            color_picker: true
            smooth_color_wheel: true
            speed: true
            intensity: true
            force_features: false
            show_slider_percent: true
            full_width_sliders: false
            brightness_icon: weather-sunny
            white_icon: file-word-box
            temperature_icon: thermometer
            speed_icon: speedometer
            intensity_icon: transit-connection-horizontal
            type: custom:light-entity-card
            entity: light.bedroom_lamp
            effects_list: false
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: automation.sleep_mode_lights
        icon: mdi:lightbulb-variant-outline
        name: Автоматизация света в зависимости от sleep mode
      - type: entities
        entities:
          - entity: switch.adaptive_lighting_bed_room
          - entity: switch.adaptive_lighting_sleep_mode_bed_room
          - entity: switch.animated_scene_flow
      - type: entities
        entities:
          - input_boolean.vacation_mode
      - graph: line
        type: sensor
        entity: sensor.co2
        detail: 1
  - title: Weather
    path: ''
    icon: mdi:weather-cloudy
    badges: []
    cards:
      - type: markdown
        content: >-
          Тут должна быть информация о  погоде, но тогда на первом экране будет
          слишком пусто
      - type: picture-elements
        elements:
          - type: state-badge
            entity: sensor.temperature
            style:
              top: 32%
              left: 40%
          - type: state-badge
            entity: sensor.humidity
            style:
              top: 32%
              left: 55%
        image: https://demo.home-assistant.io/stub_config/floorplan.png
      - graph: line
        hours_to_show: 24
        type: sensor
        entity: sensor.smart_plug_current_power
        detail: 1
      - type: entities
        entities:
          - entity: switch.smart_plug
        title: Smart Plug
  - title: Users
    path: users
    icon: mdi:account
    badges: []
    cards:
      - graph: line
        type: sensor
        entity: sensor.humidity
        detail: 1
      - graph: line
        type: sensor
        entity: sensor.temperature
        detail: 1
      - graph: line
        type: sensor
        entity: sensor.co2
        detail: 1
      - type: sensor
        entity: sensor.tvoc
        graph: line
  - title: Media
    path: media
    icon: mdi:television
    badges: []
    cards:
      - type: markdown
        content: |-
          Plex media server hosted  at http://192.168.31.105:32400/web.
          Server is hosted by main pc in bedroom.
      - type: markdown
        content: >-
          ## Расписание


          | Tables        | Are           |

          | ------------- |:-------------:| 

          | {{ states("sensor.charging_time") }} | Включается розетка для
          зарядки всякого разного |  

          | {{ states("sensor.wake_up_light_start_time") }} | Включается
          лампа-рассвет |  

          | {{ states("sensor.alarm_clock") }} | Отключатеся режим сна  | 

          | {{ states("sensor.weather_notifitcations") }} | Отправляется
          уведомление о погоде |  


           
  - title: Network
    path: router
    icon: mdi:access-point
    badges: []
    cards:
      - type: markdown
        content: 'Full router settings in http://router.miwifi.com/ '
        title: Info
      - type: gauge
        entity: sensor.speedtest_download
        min: 0
        max: 100
      - type: entities
        entities:
          - entity: sensor.speedtest_ping
      - type: custom:mini-graph-card
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
  - title: System
    path: system
    icon: mdi:server
    badges: []
    cards:
      - type: gauge
        entity: sensor.processor_use_percent
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 75
      - type: gauge
        entity: sensor.memory_use_percent
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 75
      - type: gauge
        entity: sensor.disk_use_percent
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 75
      - type: entities
        entities:
          - sensor.time_online
      - type: entities
        entities:
          - entity: binary_sensor.backups_stale
          - entity: sensor.backup_state
      - type: entities
        entities:
          - sensor.disk_free
      - type: entities
        entities:
          - entity: sensor.processor_temperature
          - entity: binary_sensor.rpi_power_status
      - type: thermostat
        entity: climate.rpi_cooling_fan_controller
