title: Home
views:
  - path: default_view
    title: Home
    icon: mdi:home
    badges:
      - entity: binary_sensor.updater
      - entity: person.alexander
      - entity: sun.sun
    cards:
      - type: custom:weather-card
        entity: weather.openweathermap_2
        hourly_forecast: true
        forecast: true
        details: true
        current: true
        number_of_forecasts: '3'
        name: болотце
      - type: entities
        entities:
          - entity: input_datetime.weather_notification
          - entity: input_boolean.weather_notification_weekdays
      - type: entities
        entities:
          - entity: sensor.openweathermap_rain_2
          - entity: sensor.openweathermap_snow_2
          - entity: sensor.openweathermap_humidity_2
          - entity: sensor.openweathermap_pressure_2
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.living_room_temperature
            line_color: var(--accent-color)
            line_width: 8
            font_size: 75
          - type: custom:mini-graph-card
            entities:
              - sensor.living_room_humidity
            line_color: green
            line_width: 8
            font_size: 75
      - type: vertical-stack
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.mibedsidelamp2_7744
            icon: ''
            name: Ночник
            show_state: false
          - shorten_cards: false
            consolidate_entities: false
            child_card: true
            hide_header: true
            header: Midesklamp1s_f86f
            color_wheel: true
            persist_features: false
            brightness: true
            color_temp: true
            white_value: true
            color_picker: true
            smooth_color_wheel: true
            speed: true
            intensity: true
            force_features: false
            show_slider_percent: true
            full_width_sliders: false
            brightness_icon: weather-sunny
            white_icon: file-word-box
            temperature_icon: thermometer
            speed_icon: speedometer
            intensity_icon: transit-connection-horizontal
            type: custom:light-entity-card
            entity: light.mibedsidelamp2_7744
            effects_list: false
      - type: button
        tap_action:
          action: toggle
        entity: switch.fluxer
  - title: Weather
    path: ''
    icon: mdi:weather-cloudy
    badges: []
    cards:
      - type: markdown
        content: >-
          Тут должна быть информация о  погоде, но тогда на первом экране будет
          слишком пусто
      - type: picture-elements
        elements:
          - type: state-badge
            entity: sensor.living_room_temperature
            style:
              top: 32%
              left: 40%
          - type: state-badge
            entity: sensor.living_room_humidity
            style:
              top: 32%
              left: 55%
        image: https://demo.home-assistant.io/stub_config/floorplan.png
      - type: glance
        entities:
          - entity: input_select.sleep_mode
  - title: Users
    path: users
    icon: mdi:account
    badges: []
    cards:
      - type: history-graph
        entities:
          - entity: device_tracker.alexandersphone
          - entity: device_tracker.irinasphone
        hours_to_show: 15
        refresh_interval: 0
      - type: map
        entities:
          - entity: person.alexander
          - entity: person.irina
        hours_to_show: 0
  - title: Media
    path: media
    icon: mdi:television
    badges: []
    cards:
      - type: media-control
        entity: media_player.samsung_lt24h390
      - type: markdown
        content: |-
          Plex media server hosted  at http://192.168.31.105:32400/web.
          Server is hosted by main pc in bedroom.
  - title: Network
    path: router
    icon: mdi:access-point
    badges: []
    cards:
      - type: markdown
        content: 'Full router settings in http://router.miwifi.com/ '
        title: Info
      - type: gauge
        entity: sensor.speedtest_download
        min: 0
        max: 100
      - type: entities
        entities:
          - entity: sensor.speedtest_ping
      - type: custom:mini-graph-card
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
  - title: System
    path: system
    icon: mdi:server
    badges: []
    cards:
      - type: gauge
        entity: sensor.processor_use_percent
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 75
      - type: gauge
        entity: sensor.memory_use_percent
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 75
      - type: gauge
        entity: sensor.disk_use_percent
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 75
      - type: entities
        entities:
          - sensor.time_online
      - type: entities
        entities:
          - entity: sensor.snapshot_backup
          - entity: binary_sensor.snapshots_stale
      - type: entities
        entities:
          - sensor.disk_free
      - type: entities
        entities:
          - entity: sensor.processor_temperature
          - entity: binary_sensor.rpi_power_status
      - type: thermostat
        entity: climate.rpi_cooling_fan_controller
