title: Home
views:
  - path: default_view
    title: Home
    icon: mdi:home
    badges:
      - entity: person.alexander
      - entity: sun.sun
    cards:
      - type: custom:clock-weather-card
        entity: weather.forecast_home
        weather_icon_type: line
        animated_icon: true
        forecast_rows: 7
        locale: ru
        time_format: 24
        card_mod:
          style:
            .: |
              ha-card {
                background: none;
                border: 0;
                --ha-card-box-shadow: 0px;
                margin: -8px -4px -4px -8px;
              }
      - type: entities
        entities:
          - entity: input_boolean.alarm_clock
          - entity: input_select.sleep_mode
            secondary_info: none
      - type: markdown
        content: >-
          | Tables        | Are           |

          | ------------- |:-------------:|

          | {{ states("sensor.charging_time") }} | Включается розетка для
          зарядки всякого разного |

          | {{ states("sensor.wake_up_light_start_time") }} | Включается
          лампа-рассвет |

          | {{ states("sensor.alarm_clock") }} | Будильник, отключается режим
          сна  |

          | {{ states("sensor.weather_notifitcations") }} | Отправляется
          уведомление о погоде |

          | {{ states("input_datetime.wind_down") }} | Идет уход ко сну
        title: Расписание
      - type: entities
        entities:
          - sensor.livingroom_iaq_level
      - type: vertical-stack
        view_layout:
          grid-area: devices
        cards:
          - type: custom:bubble-card
            card_type: separator
            name: Качество воздуха
            icon: mdi:devices
            styles: |-
              .bubble-line {
                background: var(--ha-card-background);
                opacity: 1;
              }
          - square: false
            type: grid
            columns: 3
            cards:
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.livingroom_iaq_level
                    attribute: temperature_index
                    name: Температура
                show:
                  labels: true
                color_thresholds:
                  - value: 1
                    color: '#ff0000'
                  - value: 2
                    color: '#ff8c00'
                  - value: 3
                    color: '#fcff00'
                  - value: 4
                    color: '#91ff00'
                  - value: 5
                    color: '#00ff23'
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.livingroom_iaq_level
                    attribute: humidity_index
                    name: Влажность
                show:
                  labels: true
                color_thresholds:
                  - value: 1
                    color: '#ff0000'
                  - value: 2
                    color: '#ff8c00'
                  - value: 3
                    color: '#fcff00'
                  - value: 4
                    color: '#91ff00'
                  - value: 5
                    color: '#00ff23'
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.livingroom_iaq_level
                    attribute: co2_index
                    name: CO2
                show:
                  labels: true
                color_thresholds:
                  - value: 1
                    color: '#ff0000'
                  - value: 2
                    color: '#ff8c00'
                  - value: 3
                    color: '#fcff00'
                  - value: 4
                    color: '#91ff00'
                  - value: 5
                    color: '#00ff23'
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.livingroom_iaq_level
                    attribute: tvoc_index
                    name: TVoc
                show:
                  labels: true
                color_thresholds:
                  - value: 1
                    color: '#ff0000'
                  - value: 2
                    color: '#ff8c00'
                  - value: 3
                    color: '#fcff00'
                  - value: 4
                    color: '#91ff00'
                  - value: 5
                    color: '#00ff23'
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.livingroom_iaq_level
                    attribute: pm_index
                    name: PM
                show:
                  labels: true
                color_thresholds:
                  - value: 1
                    color: '#ff0000'
                  - value: 2
                    color: '#ff8c00'
                  - value: 3
                    color: '#fcff00'
                  - value: 4
                    color: '#91ff00'
                  - value: 5
                    color: '#00ff23'
      - type: entities
        entities:
          - entity: sensor.air_temperature
          - entity: sensor.air_humidity
  - title: Living room
    path: users
    icon: mdi:television
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.living_room_lights
          - shorten_cards: false
            consolidate_entities: true
            child_card: false
            hide_header: false
            show_header_icon: false
            header: ''
            color_wheel: true
            persist_features: false
            brightness: true
            color_temp: true
            white_value: true
            color_picker: true
            speed: true
            intensity: true
            force_features: false
            show_slider_percent: false
            full_width_sliders: false
            brightness_icon: weather-sunny
            white_icon: file-word-box
            temperature_icon: thermometer
            speed_icon: speedometer
            intensity_icon: transit-connection-horizontal
            type: custom:light-entity-card
            entity: light.living_room_lights
            effects_list: false
      - type: entities
        entities:
          - entity: switch.adaptive_lighting_living_room
          - entity: switch.adaptive_lighting_sleep_mode_living_room
      - type: vertical-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.smart_plug_current_power
          - type: entities
            entities:
              - entity: switch.smart_plug
  - title: Bedroom
    path: ''
    icon: mdi:bed-queen
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: light.bedroom_lamp
            icon: mdi:lamp
            name: Ночник
            show_state: false
          - shorten_cards: false
            consolidate_entities: false
            child_card: true
            hide_header: true
            show_header_icon: false
            header: Midesklamp1s_f86f
            color_wheel: true
            persist_features: false
            brightness: true
            color_temp: true
            white_value: true
            color_picker: true
            speed: true
            intensity: true
            force_features: false
            show_slider_percent: true
            full_width_sliders: false
            brightness_icon: weather-sunny
            white_icon: file-word-box
            temperature_icon: thermometer
            speed_icon: speedometer
            intensity_icon: transit-connection-horizontal
            smooth_color_wheel: true
            type: custom:light-entity-card
            entity: light.bedroom_lamp
            effects_list: false
  - title: Network
    path: router
    icon: mdi:access-point
    badges: []
    cards:
      - type: entities
        entities:
          - entity: binary_sensor.keenetic_giga_kn_1011_connectivity
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: button
            button_type: name
            name: Client list
            icon: mdi:home
            tap_action:
              action: url
              url_path: http://192.168.1.1/controlPanel/devicesList
          - type: custom:bubble-card
            card_type: button
            button_type: name
            name: Dashboard
            tap_action:
              action: url
              url_path: http://192.168.1.1/dashboard
            icon: mdi:access-point-network
  - title: System
    path: system
    icon: mdi:server
    badges: []
    cards:
      - type: gauge
        entity: sensor.processor_use_percent
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 75
      - type: entities
        entities:
          - sensor.time_online
      - type: gauge
        entity: sensor.disk_use_percent
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 75
      - type: entities
        entities:
          - entity: binary_sensor.backups_stale
          - entity: sensor.backup_state
      - type: gauge
        entity: sensor.memory_use_percent
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 75
      - type: entities
        entities:
          - entity: sensor.processor_temperature
          - entity: binary_sensor.rpi_power_status
      - type: thermostat
        entity: climate.rpi_cooling_fan_controller
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: button
            button_type: name
            name: Grafana
            icon: phu:grafana
            tap_action:
              url_path: ''
            button_action:
              tap_action:
                action: url
                url_path: http://192.168.1.136:8888/
          - type: custom:bubble-card
            card_type: button
            button_type: name
            name: Portainer
            icon: mdi:docker
            tap_action:
              url_path: ''
            button_action:
              tap_action:
                action: url
                url_path: https://192.168.1.136:9443/
          - type: custom:bubble-card
            card_type: button
            button_type: name
            name: Dashboard
            tap_action:
              url_path: ''
            icon: phu:prometheusio
            button_action:
              tap_action:
                action: url
                url_path: http://192.168.1.136:9090/
          - type: custom:bubble-card
            card_type: button
            button_type: name
            name: Photoprism
            tap_action:
              url_path: ''
            icon: mdi:camera
            button_action:
              tap_action:
                action: url
                url_path: http://192.168.1.136:2342/
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: button
            button_type: name
            name: InfluxDB
            tap_action:
              url_path: ''
            icon: mdi:database
            button_action:
              tap_action:
                action: url
                url_path: http://192.168.1.136:8086/
